### PR TITLE
[MM-107] Update plugin with respect to phase 1 upgrades

### PR DESCRIPTION
**Pull request by ayusht2810**
#### Summary
Updated plugin with respect to phase 1 upgrades

- Updated build folder
- Updated Makefile
- Update Go version.
- Updated version in `nvmrc` file.
- Updated developer docs link in the readme file 
- Updated package in go modules to use https://pkg.go.dev/github.com/mattermost/mattermost/server/public.

#### Ticket Link

### CODE REVIEW

**Review by mickmister — APPROVED** [review]

**Comment by ayusht2810** [comment]
@mickmister Should we assign a QA to test the PR?

**Comment by mickmister** [comment]
I think we can delay to release testing on these PRs. On a side note, I wonder why CI is not running properly here. There are no GitHub actions running. Note that we want to include the changes from https://github.com/mattermost/mattermost-plugin-starter-template/pull/192 here

**Comment by ayusht2810** [comment]
@mickmister synced the PR with the starter template to include some more changes.

**Comment by mickmister** [comment]
@toninis Any ideas why CI is not running on this PR?

**Review by mickmister — APPROVED** [review]

**Comment by mickmister** [comment]
@ayusht2810 Can you please run the CI commands locally?

**Comment by Kshitij-Katiyar** [comment]
> @ayusht2810 Can you please run the CI commands locally?

@mickmister Done it is running successfully.

**Comment by mickmister** [comment]
@toninis CI is not running for this plugin PR nor https://github.com/mattermost/mattermost-plugin-webex/pull/75. Any idea why this may be the case?

**Comment by mickmister** [comment]
@raghavaggarwal2308 Can you please give this PR a review?

**Comment by toninis** [comment]
@ayusht2810 please create a new empty commit to retrigger the worfklow 
```
git commit --allow-empty -m "Empty-Commit to retrigger workflow" ; git push
```

**Review by raghavaggarwal2308 — APPROVED** [review]

**Comment by Kshitij-Katiyar** [comment]
> @ayusht2810 please create a new empty commit to retrigger the worfklow
> 
> ```
> git commit --allow-empty -m "Empty-Commit to retrigger workflow" ; git push
> ```

@toninis Pushed an empty commit but i don't think the workflows have been triggered here.

**Comment by mickmister** [comment]
@Kshitij-Katiyar It looks like the workflows have run now

**Review by AayushChaudhary0001 — APPROVED** [review]
Tested this PR, working fine for all the major functionalities, LGTM. Approved.
(Tested on MM version 9+ and 7.8.0 since the plugin is not working perfectly on the minimum supported version)

**Pull request merged**
